Restaurant Profile Page with Mocked Data - RPF001/002
danielsespitia/proyecto-top pull request #10
Opened 2020-11-17 16:55 UTC by danielsespitia

Restaurant Profile Page now displays mocked data. Added the buttons "Sucursales" and "Editar tu Perfil" which are not functional yet and implemented styles.

New files created: 

-[x] YourProfile.js (component)

![your-profile](https://user-images.githubusercontent.com/63252057/99420628-6f8e4900-28cb-11eb-8c8e-9f19f0bd8fe1.png)

2020-11-17 17:04 UTC, simonhoyos requested changes

2020-11-17 17:04 UTC, simonhoyos commented on alamesa/src/components/styled/DesktopStructure.js
> +  //grid-template-columns: repeat(4, 1fr);
es mejor no dejar comentarios

2020-11-17 17:04 UTC, simonhoyos commented on alamesa/src/pages/RestaurantProfile.js
> +    id: uuidv4(),
ojo este bloque tiene una identación adicional

2020-11-17 17:04 UTC, simonhoyos commented on alamesa/src/pages/RestaurantProfile.js
> +const profileData = [{
Profile data pueden se varios elementos? o siempre va a ser uno?

2020-11-17 17:04 UTC, simonhoyos commented on alamesa/src/pages/RestaurantProfile.js
> +                <Lnk>
Qué es Lnk y LnkA, es recomendable ponerles nombres más Descriptivos a los componentes

2020-11-19 16:02 UTC, SergioJaramilloL approved these changes, later dismissed

2020-11-19 16:03 UTC, carosalazar28 commented on alamesa/src/pages/RestaurantProfile.js
> +                  <MyOfficesAnchor>Sucursales</MyOfficesAnchor>
Yo sacaría esa etiqueta anchor de esa etiqueta parragraph y le pasaría los estilos solo a anchor, solo como comentario pero si lo ves bien así Ok

2020-11-19 16:54 UTC, simonhoyos requested changes

2020-11-19 16:54 UTC, simonhoyos commented on alamesa/src/pages/RestaurantProfile.js
> +const profileData = [
Profile data no lo manejaria como un arreglo. La data del perfil solo es de un restaurante (la parte del arreglo sobra) y lo dejaria como un solo objeto

2020-11-19 16:54 UTC, simonhoyos commented on alamesa/src/pages/RestaurantProfile.js
> +        {!!profileData && profileData.map(({ id, restaurantName, address, phone, scheduleFrom, scheduleTo, deposit }) => {
si manejamos el profileData como un solo objeto no tenemos que hacer el map porque solo es un elemento

2020-11-19 18:17 UTC, carosalazar28 submitted a review, later dismissed

2020-11-19 19:08 UTC, danielsespitia commented on alamesa/src/pages/RestaurantProfile.js
> +const profileData = [
listo, cambiado por objeto aquí y en el render

2020-11-19 19:36 UTC, carosalazar28 approved these changes

2020-11-19 22:52 UTC, simonhoyos approved these changes

2020-11-20 00:53 UTC, andress20 approved these changes

2020-11-20 01:05 UTC, merged