Feature hom003
danielsespitia/proyecto-top pull request #24
Opened 2020-11-26 16:18 UTC by carosalazar28

**Created context for change the header when the user are conected.**

**Files change:**

- Folder store with file AuthContext.js -> contain the global context.
- Import useContext and AuthContext in Header.js -> get the logic with ternary operator, add styles for the new elements
- Import AuthContext in SignIn and SignUp -> get the method created in AuthContext for the action when the user have token
- Import AuthContext and AuthProvider in index.js -> wrap all the App.js in the provider global context

**_Header when the user is logout:_**

![image](https://user-images.githubusercontent.com/65572735/100373487-d8b34200-2fd8-11eb-8f6b-1f71a4cf1c10.png)

**_Header when the user is login_**
![image](https://user-images.githubusercontent.com/65572735/100373539-ecf73f00-2fd8-11eb-9691-fd4362374295.png)

The button 'Cerrar sesión'  change the header and go to home page

2020-11-26 17:49 UTC, SergioJaramilloL approved these changes, later dismissed

2020-11-26 19:24 UTC, simonhoyos approved these changes, later dismissed

2020-11-26 19:24 UTC, simonhoyos commented on src/store/AuthContext.js
> +  const [token, setToken] = useState(false)
Qué pasa si refrescas la página después de hacer login?

2020-11-26 19:26 UTC, andress20 approved these changes

2020-11-27 15:28 UTC, andress20 requested changes

2020-11-27 15:28 UTC, andress20 commented on src/pages/SignUp.js
> +          url: `/${isUserType}/sign-up`,
- [x] Este operador ternario `isUserType` sobra. Podemos utilizar directamente la variable `userType`

2020-11-27 19:30 UTC, andress20 approved these changes

2020-11-27 19:55 UTC, danielsespitia approved these changes

2020-11-27 20:02 UTC, SergioJaramilloL approved these changes

2020-11-27 21:08 UTC, simonhoyos approved these changes

2020-11-27 21:10 UTC, merged