feature rpf003
danielsespitia/proyecto-top pull request #33
Opened 2020-11-28 22:38 UTC by danielsespitia

- Restaurant Profile now renders data sent via AXIOS through POST and GET methods.
- Added input fields to update restaurant required data for reservations.
- UPDATE and DELETE buttons aren't functional yet.

![Screen Shot 2020-11-28 at 5 34 26 PM](https://user-images.githubusercontent.com/63252057/100527410-49f12180-31a0-11eb-9274-eeb18d4b9b82.png)

2020-11-28 23:01 UTC, andress20 commented
Este PR te quedó apuntando a main.

2020-11-29 14:36 UTC, simonhoyos commented
Ojo, este PR está apuntando a main

2020-11-29 19:18 UTC, carosalazar28 requested changes

2020-11-29 19:18 UTC, carosalazar28 commented on src/components/Footer.js
> +import styled from 'styled-components'
Dani porque te están saliendo cambios en este archivo?

2020-11-29 19:18 UTC, carosalazar28 commented on src/components/FormSignIn.js
> +import { Link } from 'react-router-dom'
Igualmente en este archivo?

2020-11-29 19:18 UTC, carosalazar28 commented on src/components/RestProfileForm.js
> +      margin-right: 50px;
Se te fue doble identación

2020-11-29 19:19 UTC, carosalazar28 commented
Este pullrequest sugiero que se cierre y vuelvas a subir uno con la rama develop actualizada porque estás llevando cambios en todos los archivos

2020-11-30 15:19 UTC, andress20 requested changes

2020-11-30 15:19 UTC, andress20 commented on src/pages/RestaurantProfile.js
> +
Te quedaron console.log en el codigo.

2020-11-30 15:26 UTC, danielsespitia commented on src/pages/RestaurantProfile.js
> +
gracias Andrés

2020-11-30 15:34 UTC, andress20 approved these changes

2020-11-30 15:35 UTC, carosalazar28 approved these changes

2020-11-30 16:10 UTC, simonhoyos approved these changes

2020-11-30 16:15 UTC, merged