Feature reg001 form create account
danielsespitia/proyecto-top pull request #4
Opened 2020-11-11 21:46 UTC by carosalazar28

Create form for create account with the next input:

- [x] name

- [x] email

- [x] password

- [x] confirm password -> validate with the password

- [x] terms

- [x] user

- [x] botton

![image](https://user-images.githubusercontent.com/65572735/98867954-6de10300-243d-11eb-9ebc-17caac712633.png)

2020-11-11 21:59 UTC, SergioJaramilloL submitted a review, later dismissed

2020-11-11 22:02 UTC, simonhoyos commented
Este pull request va para main o para develop? @carosalazar28

2020-11-11 22:21 UTC, carosalazar28 commented
> Este pull request va para main o para develop? @carosalazar28

Para develop, ya lo cambie

2020-11-11 22:46 UTC, danielsespitia submitted a review, later dismissed

2020-11-11 22:49 UTC, andress20 approved these changes, later dismissed
En el App.js quedo una identación de 4.(en el return).

2020-11-11 22:52 UTC, carosalazar28 commented
> En el App.js quedo una identación de 4.(en el return).

Listo ya quedo resuelto y revise para colocar los ';'

2020-11-11 22:55 UTC, andress20 approved these changes, later dismissed

2020-11-11 22:56 UTC, simonhoyos requested changes

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/App.js
> +import Header from './components/Header'
Veo que hay código relacionado con el Header, eso es correcto?

Idealmente es mejor tener ramas especificas, o en las que se desarrolla una sola tarea para que no hayan confusiones.

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/App.js
> +					<Route exact path='/SignUp' component={FormSignUp}/>
acá `path="/SignUp"` se usa para formar la url y no como variable. te recomiendo mejos usar minúsculas y separar las palabras con un guión (-) `sign-up`

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/components/Header.js
> +            <Anchor to="./">Restaurantes</Anchor>
Acá no es necesario tener rutas relativas. Puedes dejar simplemente `to="/"`. Este comentario es valido para los siguientes Anchor también.

Otra cosa, en este caso estas definiendo los valores de los props con comillas dobles, pero en App los defines usando comillas simples. Es mejor usar un solo tipo (normalmente se usan comillas dobles en jsx)

P.s. las comillas entre el código `js` y `jsx` pueden ser diferentes. Ej: yo en js uso comillas simples y en jsx uso siempre comillas dobles

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/components/styled/ContainerContent.js
> +  props => props.theme.grayColorOverlay
Si agregas un nivel de indentación en esta línea puede ser más fácil entender que hace parte del código de la línea anterior

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/components/styled/ButtonPrimary.js
> +const ButtonPrimary = styled.input`
Alguna razón especifica para usar input y no button?

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/pages/FormSignUp.js
> +const Button = styled(ButtonPrimary)`
Si no va a tener estilos extra podemos usar simplemente `ButtonPrimary`

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/pages/FormSignUp.js
> +const Main = styled(ContainerContent)`
Si no va a tener estilos extra podemos usar simplemente `ContainerContent`

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/pages/FormSignUp.js
> +    console.log(this.state);
Es mejor no dejar console.logs en el código

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/pages/FormSignUp.js
> +      <Main>
Alguna razón para usar main en este componente? este es el contenido principal de la página?

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/pages/FormSignUp.js
> +          >Tipo de Usuario:
Tipo de Usuario lo pondría en la siguiente línea

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/pages/FormSignUp.js
> +            <option value='cliente'>
En el futuro sería bueno que estas opciones se rendericen dinámicamente

2020-11-11 22:56 UTC, simonhoyos commented on alamesa/src/App.js
> +		<Router>
Ojo con la identación. Que sea consistente con el resto del proyecto

2020-11-11 23:01 UTC, carosalazar28 commented on alamesa/src/App.js
> +import Header from './components/Header'
Como así Simon? en el Header están los hipervínculos para renderizar otras paginas, pero no entiendo lo que me dices.

2020-11-11 23:11 UTC, carosalazar28 commented on alamesa/src/components/styled/ButtonPrimary.js
> +const ButtonPrimary = styled.input`
Según lo que nos hablabas en clase, que por semántica ayuda a que el usuario solo tenga que darle tap al form para utilizarlo, La idea seria utilizar input en los formularios y botones para otras acciones

2020-11-11 23:12 UTC, carosalazar28 commented on alamesa/src/pages/FormSignUp.js
> +      <Main>
Si es el contenido principal de la página

2020-11-11 23:14 UTC, carosalazar28 commented on alamesa/src/App.js
> +		<Router>
Si, la identación de App.js no se está mostrando bien:

![image](https://user-images.githubusercontent.com/65572735/98875204-b7374f80-2449-11eb-9686-ab6a29d70a4b.png)

2020-11-11 23:17 UTC, carosalazar28 commented on alamesa/src/pages/FormSignUp.js
> +            <option value='cliente'>
A que te refieres con esto?

2020-11-12 13:29 UTC, simonhoyos commented on alamesa/src/App.js
> +import Header from './components/Header'
Por ejemplo yo tengo una rama feature-header-component y otra que se llama feature-login-form la idea es que en feature-header-component este todo lo relacionado con el header y en feature-login-form todo lo relacionado con el form y tratar de no tener código de la tarea del header en login-form

2020-11-12 13:30 UTC, simonhoyos commented on alamesa/src/pages/FormSignUp.js
> +            <option value='cliente'>
en el futuro esto puede ser un arreglo con los datos y usando el método map renderizamos todo el listado de opciones. Si en el futuro se quieren agregar más opciones solo es agregarlas al arreglo

2020-11-12 15:03 UTC, simonhoyos requested changes

2020-11-12 15:03 UTC, simonhoyos commented on alamesa/src/App.js
> +		<Header></Header>
Ojo la identación en este archivo está configurada a 2 tabs y no a 2 espacios como el resto de la aplicación

2020-11-12 15:03 UTC, simonhoyos commented
Un último cambio pequeñito y quedamos listos para el merge

2020-11-12 15:47 UTC, simonhoyos approved these changes

2020-11-12 15:49 UTC, andress20 approved these changes

2020-11-12 15:54 UTC, danielsespitia approved these changes

2020-11-12 15:54 UTC, merged