Feature RLS001 restaurant list
danielsespitia/proyecto-top pull request #5
Opened 2020-11-12 21:56 UTC by andress20

Create Restaurnt List Page.

The feature is just to show the current resturants in the platform. List them without any order (for now). The list getting fill with mock data in a separete file. 

Restaurant item only include Logo, Name and access button (no functional just the button). And the list is located leaving space in the left side of the screen for a future menu.

Finally we are link it the list with the button in the header component.

- [ ] Restaurants.js (page in the router component)
- [ ] Restaurants.js ( function whom render the list)
- [ ] Data.js (mock data)
- [ ] Header.js (to link the list in the header menu)

![ResturantList](https://user-images.githubusercontent.com/8940946/99000431-42c2e600-2507-11eb-93b6-ff10670c7744.png)

2020-11-12 22:05 UTC, SergioJaramilloL submitted a review, later dismissed

2020-11-12 23:24 UTC, simonhoyos requested changes

2020-11-12 23:24 UTC, simonhoyos commented on alamesa/src/components/Restaurant.js
> +  height: 120px;
ojo con la identación. los demás archivos están identados a 2 espacios y los nuevos archivos estan identados a 4 espacios o un tab

2020-11-12 23:24 UTC, simonhoyos commented on alamesa/src/components/Restaurant.js
> +	type: button;
el tipo del botón es un atributo o prop del componente y no una propiedad de css.

2020-11-12 23:24 UTC, simonhoyos commented on alamesa/src/components/Restaurant.js
> +				<Button>
Acá es donde tienes que poner el tipo

2020-11-12 23:24 UTC, simonhoyos commented on alamesa/src/components/Restaurant.js
> +  object-fit: cover;
Object-fit no tiene soporte en el 100% de los navegadores y en algunas versiones. Te recomiendo probarlo en Safari más que todo

2020-11-12 23:24 UTC, simonhoyos commented on alamesa/src/pages/Restaurants.js
> +								<Restaurant
Recuerda pasarle el prop `key` a las listas. En el mock data podrías agregar un id a los elementos

2020-11-12 23:24 UTC, simonhoyos commented on alamesa/src/pages/Restaurants.js
> +		name: data
Trata de ponerle un nombre más significativo al estado. En vez de name podrías usar restaurants

2020-11-12 23:24 UTC, simonhoyos commented on alamesa/src/Data.js
> +		name: 'Mister Wok',
Sería bueno agregarle más datos a los restaurantes. Podrías agregarle la imagen o el logo del restaurante acá. No importa que todos sean lo mismo, tenerlo dentro del objeto se acerca más a la realidad que tener una imagen quemada en el jsx para todos los elementos

2020-11-13 00:08 UTC, andress20 commented on alamesa/src/components/Restaurant.js
> +  height: 120px;
Si tengo super presente la identación, de hecho la vulevo a revisar y esta bien en mi editor. La tengo a 2 espacios (el tab tambien marca 2 espacios). Arreglaré los otros comentarios y a la proxima espero salga bien la identación. Gracias!

![identacion](https://user-images.githubusercontent.com/8940946/99011458-2b412880-251a-11eb-9738-9e11addfea38.png)

2020-11-13 00:45 UTC, carosalazar28 commented on alamesa/src/pages/Restaurants.js
> +`
Siempre toca poner **;** al terminar de declarar las reglas de css

2020-11-13 03:33 UTC, andress20 commented on alamesa/src/components/Restaurant.js
> +  object-fit: cover;
La otra opción que encontré para cambiar `Object-fit` es `background-size`. Aunque probando veo que si la elimino del todo no me afecta en la imagen que estoy colocando. La coloqué para que independientemente del tamaño de imagen que pasaramos ahi, esta se acomodara al espacio que tenemos designado para el logo del restaurante. Me recomiendas eliminarla o dejar el background?

No encontré forma de instalar safari en Linux (Ubuntu) pero si pude instalar epiphany que maneja el mismo motor de renderizado de safari **WebKit** a lo mejor no es 100% fidedigno pero me ayudará a tener una idea del comportamiento en safari por ahora.

2020-11-13 05:31 UTC, andress20 commented on alamesa/src/pages/Restaurants.js
> +								<Restaurant
Listo prop `key` agregado, y id para los elementos con uuid().

2020-11-13 05:34 UTC, andress20 commented on alamesa/src/pages/Restaurants.js
> +`
Listo bien. Ya los agregué.

2020-11-13 12:40 UTC, danielsespitia submitted a review, later dismissed

2020-11-13 13:40 UTC, carosalazar28 commented on alamesa/src/components/Restaurant.js
> +  height: 120px;
Acá se te fue mal una identación

2020-11-13 13:40 UTC, carosalazar28 submitted a review, later dismissed

2020-11-13 15:38 UTC, andress20 commented on alamesa/src/components/Restaurant.js
> +  height: 120px;
Listo, creo que es cosa de configuración en mi editor. Ya le movi algunas cosas en esa configuración para corregir eso.

2020-11-13 16:18 UTC, simonhoyos commented on alamesa/src/components/Restaurant.js
> +  object-fit: cover;
super, no hay problema. Por ahora solo es para que lo tengan en cuenta, que a veces hay que probar en otros navegadores para ver que todo funcione

2020-11-13 19:26 UTC, simonhoyos requested changes

2020-11-13 19:26 UTC, simonhoyos commented on alamesa/src/components/Restaurant.js
> +				src={logo}
la identación en este archivo sigue a 4 espacios. Creo que te toca hacer el arreglo manualmente

2020-11-13 19:26 UTC, simonhoyos commented on alamesa/src/pages/Restaurants.js
>  			<Container>
la identación en este archivo sigue a 4 espacios. Creo que te toca hacer el arreglo manualmente

2020-11-13 20:51 UTC, andress20 commented on alamesa/src/components/Restaurant.js
> +				src={logo}
Listo, hice 2 push muy seguidos como 5 minutos de diferencia. Ya le veo bien la identacion simon. de hecho aparece la palabra "Outdated" al frente de la ruta de este archivo en tu comentrio supongo que porque el archivo ya cambio no se. Pero ya puedes volver a revisar.

2020-11-13 20:51 UTC, andress20 commented on alamesa/src/pages/Restaurants.js
>  			<Container>
Archivo actualizado!

2020-11-13 21:03 UTC, carosalazar28 approved these changes

2020-11-13 21:35 UTC, simonhoyos approved these changes

2020-11-13 22:58 UTC, danielsespitia approved these changes

2020-11-13 22:59 UTC, merged