Feature rpf001/002
danielsespitia/proyecto-top pull request #6
Opened 2020-11-13 17:04 UTC by danielsespitia

Created Restaurant Profile Form Page.

Once the user is registered as Restaurant, this feature redirects them to a form designed to store basic data about the Restaurant such as name, address, phone, opening and closing hours and a minimum deposit required to schedule a reservation from the client end.

The opening and closing hours and deposit fields values are subject to form validation in order to submit just permitted values.

The Restaurant Profile Form Page contains a form with a submit button that is routed to 'your-profile' page (which doesn't have any rendered data other than its title yet).

Since the data is not being printed yet, console.log is included in the code in order to show the updated form data in the console.

The pages and components created for this feature were:

[ x ] RestaurantForm.js
[ x ] RestProfileForm.js
[ x ] YourRprofile.js

![1Page](https://user-images.githubusercontent.com/63252057/99099377-5a05e000-25a8-11eb-9da9-c85fbfa6baa4.png)
![2RequiredHour](https://user-images.githubusercontent.com/63252057/99099383-5b370d00-25a8-11eb-9fb1-e6fa3daae158.png)
![3Required Deposit](https://user-images.githubusercontent.com/63252057/99099386-5d00d080-25a8-11eb-978e-8a4237b25067.png)
![4PageRouting](https://user-images.githubusercontent.com/63252057/99099394-5f632a80-25a8-11eb-84ec-161539e97314.png)

2020-11-13 21:13 UTC, carosalazar28 submitted a review, later dismissed

2020-11-13 21:33 UTC, simonhoyos requested changes

2020-11-13 21:33 UTC, simonhoyos commented on alamesa/src/App.js
> +import YourRprofile from './pages/YourRprofile'
yo le cambiaria el nombre al componente. El nombre es importante para darnos una idea de lo que hace. Un ejemplo `RestaurantProfile`

2020-11-13 21:33 UTC, simonhoyos commented on alamesa/src/pages/RestaurantForm.js
> +    this.setState({ [name]: value }, () => console.log('current', this.state))
Es importante no dejar console.logs en el código que ya está listo (hay algunas excepciones)

2020-11-13 21:33 UTC, simonhoyos commented on alamesa/src/pages/YourRprofile.js
> +function YourRprofile() {
Lo mismo de cambiar el nombre

2020-11-13 23:24 UTC, andress20 commented on alamesa/src/App.js
> +        <Route exact path='/' component={Home}/>
Quedaron 2 route apuntando a Home

2020-11-14 00:06 UTC, carosalazar28 approved these changes, later dismissed

2020-11-14 00:08 UTC, andress20 submitted a review, later dismissed

2020-11-14 02:33 UTC, andress20 approved these changes

2020-11-14 17:08 UTC, simonhoyos approved these changes

2020-11-14 17:40 UTC, SergioJaramilloL approved these changes

2020-11-14 17:49 UTC, merged