link from restaurant-profile to restaurant-profile/_restaurantId/rese…
danielsespitia/proyecto-top pull request #63
Opened 2020-12-13 21:31 UTC by SergioJaramilloL

link from restaurant-profile to restaurant-profile/_restaurantId/reservation

![Captura de pantalla de 2020-12-13 16-18-29](https://user-images.githubusercontent.com/70079208/102024525-7c824900-3d60-11eb-83b5-a8b6037e22e2.png)
![Captura de pantalla de 2020-12-13 16-18-36](https://user-images.githubusercontent.com/70079208/102024526-7e4c0c80-3d60-11eb-8fcd-e97da5187c5e.png)

2020-12-13 21:48 UTC, andress20 commented
El archivo `.env` no deberia salir en ningun PR. Verifica en el `.gitignore` que este el `.env`

2020-12-13 23:13 UTC, simonhoyos requested changes

2020-12-13 23:13 UTC, simonhoyos commented on .env
> +REACT_APP_SERVER_URL=http://localhost:8000
Adicional al comentario del gitignore puedes correr, luego de agregar el archivo al gitignore, el comando `git rm --cached .env`

2020-12-13 23:56 UTC, carosalazar28 requested changes

2020-12-13 23:56 UTC, carosalazar28 commented on src/App.js
> +            <Route exact path="/restaurant-profile/:restaurantId/reservations" component={RestaurantReservations}/>
Si para poder navegar a está pagina el restaurante tiene que estar logueado, sería necesario para ese :restaurantId, no sería necesario tener el restaurant-profile/reservations

@andress20  @danielsespitia  @simonhoyos

2020-12-14 03:36 UTC, SergioJaramilloL commented on src/App.js
> +            <Route exact path="/restaurant-profile/:restaurantId/reservations" component={RestaurantReservations}/>
![Captura de pantalla de 2020-12-13 22-33-21](https://user-images.githubusercontent.com/70079208/102037752-8f624100-3d93-11eb-9308-43038c700061.png)

2020-12-14 03:42 UTC, SergioJaramilloL commented on .env
> +REACT_APP_SERVER_URL=http://localhost:8000
Si tengo el .env en el .gitignore... No se que pasa.

![Captura de pantalla de 2020-12-13 22-39-25](https://user-images.githubusercontent.com/70079208/102038088-5bd3e680-3d94-11eb-98d4-9fc010cd28ef.png)

2020-12-14 11:58 UTC, simonhoyos commented on .env
> +REACT_APP_SERVER_URL=http://localhost:8000
Puedes correr el comando anterior y removerlo entonces del git. Trata de no usar `git add .` para agregar los archivos al commit, en la mayoría de los casos esto puede generar problemas porque no somos 100% conscientes de lo que se está subiendo

2020-12-14 14:58 UTC, SergioJaramilloL commented on .env
> +REACT_APP_SERVER_URL=http://localhost:8000
Listo Simón ya corrí el comando git rm --cached .env y removí el .env desde el github

2020-12-14 17:04 UTC, carosalazar28 approved these changes

2020-12-14 19:21 UTC, simonhoyos approved these changes

2020-12-14 19:58 UTC, andress20 approved these changes

2020-12-14 20:42 UTC, merged