add sanitary register, without button functionality
danielsespitia/proyecto-top pull request #7
Opened 2020-11-13 18:34 UTC by SergioJaramilloL

Create sanitary register page

Here the user selects affirmatively to each question, enters their temperature and can update their health record or cancel the action.

- [x]  SanitaryRegister.js
- [x]  App.jss (update link /sanitary-register)

![wireframe_sanitary_register](https://user-images.githubusercontent.com/70079208/99108176-f6ce7a80-25b4-11eb-8cf9-2da7dea8dd76.png)

2020-11-13 21:10 UTC, carosalazar28 requested changes

2020-11-13 21:10 UTC, carosalazar28 commented on alamesa/src/pages/SanitaryRegister.js
> +
Este espacio te sobra Sergio, recuerda que siempre va el ; luego de terminar la regla styled :

```
const ContainerList = styled(ContainerContent)`
  display: grid;
  justify-content: center;
  grid-row-gap: 10px;
`;
```

2020-11-13 21:10 UTC, carosalazar28 commented on alamesa/src/pages/SanitaryRegister.js
> +          <p>He estado en contacto con personas con sintomas de Covid19</p>
Para que se parezca un poco mas a nuestros frames deberías colocarle a las etiquetas de p un size de 11px con color de letra blue (#2F80ED)

2020-11-13 21:10 UTC, carosalazar28 commented on alamesa/src/pages/SanitaryRegister.js
> +const Temperature = styled.input`
Este estilo también puede mejorar agregandole padding

2020-11-13 21:10 UTC, carosalazar28 commented on alamesa/src/pages/SanitaryRegister.js
> +        <H3>Registro Sanitario</H3>
Autoevaluación para registro sanitario covid19, según nuestro frame, este es el title

2020-11-13 21:37 UTC, simonhoyos commented on alamesa/src/pages/SanitaryRegister.js
> +    response4: false,
Crees que sea posible ponerles nombres que sean más significativos?

2020-11-13 22:48 UTC, SergioJaramilloL commented on alamesa/src/pages/SanitaryRegister.js
> +    response4: false,
Estuve pensando en Question1, Question2.... Tu me dices si es mejor, aunque ya podría poner unas descripción de 2 palabras sobre la pregunta

2020-11-14 17:12 UTC, simonhoyos commented on alamesa/src/pages/SanitaryRegister.js
> +    response4: false,
Si, esto puede ser buena idea. Así va a ser más fácil identificar a que corresponde cada uno de estos valores

2020-11-16 21:50 UTC, simonhoyos approved these changes, later dismissed

2020-11-16 22:05 UTC, carosalazar28 submitted a review, later dismissed

2020-11-16 22:08 UTC, andress20 approved these changes, later dismissed

2020-11-17 15:07 UTC, danielsespitia approved these changes

2020-11-17 15:25 UTC, simonhoyos approved these changes

2020-11-17 16:11 UTC, andress20 approved these changes

2020-11-17 19:26 UTC, merged