Feature epayco
danielsespitia/proyecto-top pull request #90
Opened 2021-01-04 23:18 UTC by carosalazar28

**Change the information client attributes from store redux**

_Fix the props for do the payment_

_Created a component ready for do the logic and created the elements to render in response_

2021-01-04 23:43 UTC, andress20 approved these changes, later dismissed

2021-01-05 01:49 UTC, SergioJaramilloL submitted a review, later dismissed

2021-01-05 15:08 UTC, simonhoyos requested changes

2021-01-05 15:08 UTC, simonhoyos commented on src/components/ResponseReservation.js
> +    console.dir()
borrar este console

2021-01-05 15:08 UTC, simonhoyos commented on src/components/ResponseReservation.js
> +      baseURL: 'https://api.secure.payco.co',
Esta url podríamos configurarla desde las variables de entorno. Si en el futuro hay algun cambio solo va a ser necesario modificar la variable

2021-01-05 15:47 UTC, carosalazar28 commented
Put the changes required: Deleted the console.dir and put the env for the url payment

2021-01-05 16:24 UTC, simonhoyos approved these changes

2021-01-05 16:25 UTC, andress20 approved these changes

2021-01-05 21:39 UTC, danielsespitia approved these changes

2021-01-05 22:06 UTC, merged