ORD002 cancel reservation
danielsespitia/proyecto-top pull request #96
Opened 2021-01-06 19:50 UTC by andress20

Add funcionality in cancel reservation to remove reservation and go back to client profile.

![cancel reservation](https://user-images.githubusercontent.com/8940946/103813683-811fe180-502e-11eb-8a55-fbedb2cf13ef.gif)

2021-01-06 19:57 UTC, SergioJaramilloL approved these changes

2021-01-06 20:21 UTC, carosalazar28 requested changes

2021-01-06 20:21 UTC, carosalazar28 commented on src/store/actions/Reservation.actions.js
> +      swal('Tu reserva fue cancelada', '', 'info')
Si quitaste el remover el item de reserva de la pagina donde se ejecuta el handleClick, entonces deberías pasarlo acá, porque si no va a quedar eso en el localStorage

2021-01-06 20:46 UTC, simonhoyos approved these changes

2021-01-07 02:44 UTC, carosalazar28 approved these changes

2021-01-07 02:52 UTC, merged